// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzaApi.Data;

#nullable disable

namespace PizzaApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260506035041_AdjustPizzaPricesToSmallBase")]
    partial class AdjustPizzaPricesToSmallBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PizzaApi.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsGuest")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("PizzaApi.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PlacedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PizzaApi.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int?>("PizzaId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialInstructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("PizzaId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("PizzaApi.Models.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pizzas");
                });

            modelBuilder.Entity("PizzaApi.Models.Topping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Toppings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 0,
                            IsAvailable = true,
                            Name = "Tomato",
                            Price = 0.00m
                        },
                        new
                        {
                            Id = 2,
                            Category = 0,
                            IsAvailable = true,
                            Name = "BBQ",
                            Price = 0.00m
                        },
                        new
                        {
                            Id = 3,
                            Category = 0,
                            IsAvailable = true,
                            Name = "Alfredo",
                            Price = 0.00m
                        },
                        new
                        {
                            Id = 4,
                            Category = 0,
                            IsAvailable = true,
                            Name = "Buffalo",
                            Price = 0.00m
                        },
                        new
                        {
                            Id = 5,
                            Category = 0,
                            IsAvailable = true,
                            Name = "Garlic Butter",
                            Price = 0.00m
                        },
                        new
                        {
                            Id = 6,
                            Category = 0,
                            IsAvailable = true,
                            Name = "Pesto",
                            Price = 0.00m
                        },
                        new
                        {
                            Id = 7,
                            Category = 1,
                            IsAvailable = true,
                            Name = "Mozzarella",
                            Price = 0.75m
                        },
                        new
                        {
                            Id = 8,
                            Category = 1,
                            IsAvailable = true,
                            Name = "Parmesan",
                            Price = 0.75m
                        },
                        new
                        {
                            Id = 9,
                            Category = 1,
                            IsAvailable = true,
                            Name = "Feta",
                            Price = 0.75m
                        },
                        new
                        {
                            Id = 10,
                            Category = 1,
                            IsAvailable = true,
                            Name = "Cheddar",
                            Price = 0.75m
                        },
                        new
                        {
                            Id = 11,
                            Category = 1,
                            IsAvailable = true,
                            Name = "Ricotta",
                            Price = 0.75m
                        },
                        new
                        {
                            Id = 12,
                            Category = 2,
                            IsAvailable = true,
                            Name = "Pepperoni",
                            Price = 1.00m
                        },
                        new
                        {
                            Id = 13,
                            Category = 2,
                            IsAvailable = true,
                            Name = "Italian Sausage",
                            Price = 1.00m
                        },
                        new
                        {
                            Id = 14,
                            Category = 2,
                            IsAvailable = true,
                            Name = "Bacon",
                            Price = 1.00m
                        },
                        new
                        {
                            Id = 15,
                            Category = 2,
                            IsAvailable = true,
                            Name = "Canadian Bacon",
                            Price = 1.00m
                        },
                        new
                        {
                            Id = 16,
                            Category = 2,
                            IsAvailable = true,
                            Name = "Ham",
                            Price = 1.00m
                        },
                        new
                        {
                            Id = 17,
                            Category = 2,
                            IsAvailable = true,
                            Name = "Chicken",
                            Price = 1.00m
                        },
                        new
                        {
                            Id = 18,
                            Category = 3,
                            IsAvailable = true,
                            Name = "Mushrooms",
                            Price = 0.50m
                        },
                        new
                        {
                            Id = 19,
                            Category = 3,
                            IsAvailable = true,
                            Name = "Bell Peppers",
                            Price = 0.50m
                        },
                        new
                        {
                            Id = 20,
                            Category = 3,
                            IsAvailable = true,
                            Name = "Red Onions",
                            Price = 0.50m
                        },
                        new
                        {
                            Id = 21,
                            Category = 3,
                            IsAvailable = true,
                            Name = "Black Olives",
                            Price = 0.50m
                        },
                        new
                        {
                            Id = 22,
                            Category = 3,
                            IsAvailable = true,
                            Name = "Jalapeños",
                            Price = 0.50m
                        },
                        new
                        {
                            Id = 23,
                            Category = 4,
                            IsAvailable = true,
                            Name = "Hot Sauce",
                            Price = 0.50m
                        },
                        new
                        {
                            Id = 24,
                            Category = 4,
                            IsAvailable = true,
                            Name = "Honey",
                            Price = 0.50m
                        },
                        new
                        {
                            Id = 25,
                            Category = 4,
                            IsAvailable = true,
                            Name = "Hot Honey",
                            Price = 0.50m
                        },
                        new
                        {
                            Id = 26,
                            Category = 4,
                            IsAvailable = true,
                            Name = "Balsamic",
                            Price = 0.50m
                        });
                });

            modelBuilder.Entity("PizzaToppings", b =>
                {
                    b.Property<int>("PizzasId")
                        .HasColumnType("int");

                    b.Property<int>("ToppingsId")
                        .HasColumnType("int");

                    b.HasKey("PizzasId", "ToppingsId");

                    b.HasIndex("ToppingsId");

                    b.ToTable("PizzaToppings");
                });

            modelBuilder.Entity("PizzaApi.Models.Order", b =>
                {
                    b.HasOne("PizzaApi.Models.Account", "Account")
                        .WithMany("Orders")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("PizzaApi.Models.OrderItem", b =>
                {
                    b.HasOne("PizzaApi.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PizzaApi.Models.Pizza", "Pizza")
                        .WithMany()
                        .HasForeignKey("PizzaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Order");

                    b.Navigation("Pizza");
                });

            modelBuilder.Entity("PizzaToppings", b =>
                {
                    b.HasOne("PizzaApi.Models.Pizza", null)
                        .WithMany()
                        .HasForeignKey("PizzasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PizzaApi.Models.Topping", null)
                        .WithMany()
                        .HasForeignKey("ToppingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PizzaApi.Models.Account", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("PizzaApi.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
